name: stabilitySetup
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens
  - autopep8
  - bzip2
  - ca-certificates
  - certifi
  - colorama
  - comm
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - ipykernel
  - ipython
  - jedi
  - jupyter_client
  - jupyter_core
  - libffi
  - libsodium
  - matplotlib-inline
  - nest-asyncio
  - openssl
  - parso
  - pip
  - platformdirs
  - prompt-toolkit
  - psutil
  - pure_eval
  - pycodestyle
  - pygments
  - pyparsing
  - python=3.10
  - python-dateutil
  - pyzmq
  - setuptools
  - six
  - sqlite
  - stack_data
  - tk
  - toml
  - tornado
  - traitlets
  - typing_extensions
  - tzdata
  - wcwidth
  - wheel
  - xz
  - zeromq
  - zlib
  - pip:
    - altgraph
    - contourpy
    - cycler
    - dotenv
    - fonttools
    - future
    - kiwisolver
    - matplotlib
    - matplotlib-label-lines
    - more-itertools
    - numpy
    - numpy-indexed
    - packaging
    - pandas
    - pefile
    - pillow
    - pyinstaller
    - pyinstaller-hooks-contrib
    - pyserial
    - pyside6
    - pyside6-addons
    - pyside6-essentials
    - pysimplegui>=4.0.0
    - python-dotenv
    - pytz
    - shiboken6
